services:
  db:
    image: postgres:16.1
    container_name: shareit-db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: dbuser
      POSTGRES_DB: shareit
    volumes:

      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: ./server
    container_name: shareit-server
    depends_on:
      db:
        condition: service_healthy
      kafka: # Добавь зависимость здесь, чтобы сервер ждал брокера
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092 # Прокидываем адрес кафки

  gateway:
    build: ./gateway
    container_name: shareit-gateway
    depends_on:
      - server
    ports:
      - "8080:8080"
    environment:
      SHAREIT_SERVER_URL: http://server:9090

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: shareit-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: apache/kafka:latest
    container_name: shareit-kafka
    ports:
      - "9092:9092"
    environment:
      # Режим KRaft: один контейнер и за брокера, и за контроллер
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # Сеть: слушаем внутри на 9092, контроллер на 9093
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      # Рекламируем адрес "kafka" для других контейнеров (нашего сервера)
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

      # Сгенерированный ID кластера (обязателен для KRaft)
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      # Оптимизация для одного узла (чтобы не ждал репликации)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1