server.port=9090
logging.level.org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=dbuser
spring.datasource.password=12345
#---
#spring.config.activate.on-profile=ci,test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:shareit
#spring.datasource.username=test
#spring.datasource.password=test

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.kafka.consumer.group-id=shareit-group

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=ru.practicum.shareit.dto.bookingDto

spring.kafka.consumer.properties.spring.json.value.default.type=ru.practicum.shareit.dto.bookingDto.BookingOutputDto

spring.kafka.consumer.properties.spring.json.use.type.headers=false